<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Tester: /mnt/c/Users/abell/Documents/GitHub/NRE-Tester/src/Tester/InternalTest/NRE_InternalTest.hpp Source File</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.php">src</a></li><li class="navelem"><a class="el" href="dir_cd2a207beeaf887032d354dd35a22318.php">Tester</a></li><li class="navelem"><a class="el" href="dir_574d28496cbb730890ed2bed894df583.php">InternalTest</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">NRE_InternalTest.hpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_n_r_e___internal_test_8hpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;</div><div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">    #pragma once</span></div><div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;</div><div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">    #include &lt;string&gt;</span></div><div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;</div><div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    <span class="keyword">namespace </span><a class="code" href="namespace_n_r_e.php">NRE</a> {</div><div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;        <span class="keyword">namespace </span><a class="code" href="namespace_tester.php">Tester</a> {</div><div class="line"><a name="l00028"></a><span class="lineno"><a class="line" href="class_n_r_e_1_1_tester_1_1_internal_test.php">   28</a></span>&#160;            <span class="keyword">class </span><a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php">InternalTest</a> {</div><div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;                <span class="keyword">private</span> :   <span class="comment">// Fields</span></div><div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;                    std::string testCase;   </div><div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;                    std::string testName;   </div><div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;                <span class="keyword">public</span> :    <span class="comment">// Methods</span></div><div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160;                    <span class="comment">//## Constructor ##//</span></div><div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;<span class="comment"></span>                        <a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a368391c914b73f3dfde897feac112f2e">InternalTest</a>(std::string <span class="keyword">const</span>&amp; c, std::string <span class="keyword">const</span>&amp; n);</div><div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;</div><div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                    <span class="comment">//## Getter ##//</span></div><div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment"></span>                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a69f9abf82dc49c56a9bb9b65c737358e">getTestCase</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;                        std::string <span class="keyword">const</span>&amp; <a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a8f2beb5e2fc0123e4881a5d28808438b">getTestName</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;                        std::string <a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a2a0e1e8760903317b3e7bff3d30645db">getDetails</a>() <span class="keyword">const</span>;</div><div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;</div><div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;                    <span class="comment">//## Methods ##//</span></div><div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;<span class="comment"></span>                        <span class="keyword">virtual</span> <span class="keywordtype">void</span> <a class="code" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a03ce20227a8571daad015075f242107d">internalTestBody</a>() <span class="keyword">const</span> = 0;</div><div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;            };</div><div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;        }</div><div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;    }</div><div class="ttc" id="namespace_tester_php"><div class="ttname"><a href="namespace_tester.php">Tester</a></div><div class="ttdoc">Tester&amp;#39;s API. </div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php_a69f9abf82dc49c56a9bb9b65c737358e"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php#a69f9abf82dc49c56a9bb9b65c737358e">NRE::Tester::InternalTest::getTestCase</a></div><div class="ttdeci">std::string const &amp; getTestCase() const </div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.cpp:20</div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php">NRE::Tester::InternalTest</a></div><div class="ttdoc">Describe an internal test used to register a user test inside the suite. </div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.hpp:28</div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php_a03ce20227a8571daad015075f242107d"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php#a03ce20227a8571daad015075f242107d">NRE::Tester::InternalTest::internalTestBody</a></div><div class="ttdeci">virtual void internalTestBody() const =0</div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php_a8f2beb5e2fc0123e4881a5d28808438b"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php#a8f2beb5e2fc0123e4881a5d28808438b">NRE::Tester::InternalTest::getTestName</a></div><div class="ttdeci">std::string const &amp; getTestName() const </div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.cpp:24</div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php_a2a0e1e8760903317b3e7bff3d30645db"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php#a2a0e1e8760903317b3e7bff3d30645db">NRE::Tester::InternalTest::getDetails</a></div><div class="ttdeci">std::string getDetails() const </div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.cpp:28</div></div>
<div class="ttc" id="namespace_n_r_e_php"><div class="ttname"><a href="namespace_n_r_e.php">NRE</a></div><div class="ttdoc">The NearlyRealEngine&amp;#39;s global namespace. </div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.cpp:13</div></div>
<div class="ttc" id="class_n_r_e_1_1_tester_1_1_internal_test_php_a368391c914b73f3dfde897feac112f2e"><div class="ttname"><a href="class_n_r_e_1_1_tester_1_1_internal_test.php#a368391c914b73f3dfde897feac112f2e">NRE::Tester::InternalTest::InternalTest</a></div><div class="ttdeci">InternalTest(std::string const &amp;c, std::string const &amp;n)</div><div class="ttdef"><b>Definition:</b> NRE_InternalTest.cpp:16</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
