<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Tester: NRE::Tester::TestSuite Class Reference</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top" class="row"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespace_n_r_e.php">NRE</a></li><li class="navelem"><b>Tester</b></li><li class="navelem"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php">TestSuite</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pub-static-attribs">Static Public Attributes</a> &#124;
<a href="class_n_r_e_1_1_tester_1_1_test_suite-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">NRE::Tester::TestSuite Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Describe the test suite used to store all used-defined test and run them.  
 <a href="class_n_r_e_1_1_tester_1_1_test_suite.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_n_r_e___test_suite_8hpp_source.php">NRE_TestSuite.hpp</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a529a5dc5bf235399345229f5d41539f6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a529a5dc5bf235399345229f5d41539f6">addTest</a> (<a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php">InternalTest</a> *test)</td></tr>
<tr class="separator:a529a5dc5bf235399345229f5d41539f6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e059fc8f1cb49a4bba283bb05fe2b64"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a0e059fc8f1cb49a4bba283bb05fe2b64">addLog</a> (std::string const &amp;log)</td></tr>
<tr class="separator:a0e059fc8f1cb49a4bba283bb05fe2b64"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aae54422b099fc0bdb5ab24b924e0dff6"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#aae54422b099fc0bdb5ab24b924e0dff6">runAll</a> ()</td></tr>
<tr class="separator:aae54422b099fc0bdb5ab24b924e0dff6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a38fc3c6f7e8a83fd8163f57ad14b3a8d"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a38fc3c6f7e8a83fd8163f57ad14b3a8d">hasFailed</a> () const </td></tr>
<tr class="separator:a38fc3c6f7e8a83fd8163f57ad14b3a8d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a467dfe222580814ff230c472b67ed07e"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a467dfe222580814ff230c472b67ed07e">runAllTests</a> ()</td></tr>
<tr class="separator:a467dfe222580814ff230c472b67ed07e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab8f6475bda093850159149fafcf3dbb"><td class="memItemLeft" align="right" valign="top">static bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#aab8f6475bda093850159149fafcf3dbb">suiteHasFailed</a> ()</td></tr>
<tr class="separator:aab8f6475bda093850159149fafcf3dbb"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-attribs"></a>
Static Public Attributes</h2></td></tr>
<tr class="memitem:aec3b7f95f478c4369962b8c2735fd4f5"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php">TestSuite</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#aec3b7f95f478c4369962b8c2735fd4f5">suiteInstance</a></td></tr>
<tr class="separator:aec3b7f95f478c4369962b8c2735fd4f5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Describe the test suite used to store all used-defined test and run them. </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a class="anchor" id="a0e059fc8f1cb49a4bba283bb05fe2b64"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Tester::TestSuite::addLog </td>
          <td>(</td>
          <td class="paramtype">std::string const &amp;&#160;</td>
          <td class="paramname"><em>log</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Add a failed assertion log </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">log</td><td>the log to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a529a5dc5bf235399345229f5d41539f6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Tester::TestSuite::addTest </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php">InternalTest</a> *&#160;</td>
          <td class="paramname"><em>test</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Add a test in the suite </p><dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">test</td><td>the test to add </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a class="anchor" id="a38fc3c6f7e8a83fd8163f57ad14b3a8d"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Tester::TestSuite::hasFailed </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the suite has failed </dd></dl>

</div>
</div>
<a class="anchor" id="aae54422b099fc0bdb5ab24b924e0dff6"></a>
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Tester::TestSuite::runAll </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Run all the suite tests </p>

</div>
</div>
<a class="anchor" id="a467dfe222580814ff230c472b67ed07e"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void NRE::Tester::TestSuite::runAllTests </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Run all the suite instance tests </p>

</div>
</div>
<a class="anchor" id="aab8f6475bda093850159149fafcf3dbb"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool NRE::Tester::TestSuite::suiteHasFailed </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<dl class="section return"><dt>Returns</dt><dd>if the suite instance has failed </dd></dl>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a class="anchor" id="aec3b7f95f478c4369962b8c2735fd4f5"></a>
<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php">TestSuite</a> NRE::Tester::TestSuite::suiteInstance</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>The test suite instance </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Tester/src/Tester/TestSuite/<a class="el" href="_n_r_e___test_suite_8hpp_source.php">NRE_TestSuite.hpp</a></li>
<li>/mnt/c/Users/abell/Documents/GitHub/NRE-Tester/src/Tester/TestSuite/<a class="el" href="_n_r_e___test_suite_8cpp.php">NRE_TestSuite.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</body>
</html>
