<!-- HTML header for doxygen 1.8.8-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- For Mobile Devices -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta name="generator" content="Doxygen 1.8.11"/>
        <script type="text/javascript" src="../../js/jquery-2.1.1.min.js"></script>
        <title>NRE-Tester: Class Members - Functions</title>
        <!--<link href="tabs.css" rel="stylesheet" type="text/css"/>-->
        <script type="text/javascript" src="dynsections.js"></script>
        <link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
        <link href="doxygen.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" type="text/css"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
        <?php
            include '../../php/navigation.php';
            if (!isset($_COOKIE["theme"]) || $_COOKIE["theme"] == "dark") {
                echo '<link href="../../css/dark/bootstrap.css" rel="stylesheet">';
            } else {
                echo '<link href="../../css/light/bootstrap.css" rel="stylesheet">';
            }
        ?>
        <script src="../../js/bootstrap.min.js"></script>
        <script type="text/javascript" src="doxy-boot.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <header class="page-header">
                <a href="../../../index.php">
                    <img src="../../img/Logo.png" class="logo img-responsive"/>
                </a>
            </header>
            <?php addNavigationBarInl(false); ?>
            <div id="top"><!-- do not remove this div, it is closed by doxygen! -->
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom: 15px;">
                                <div style="margin-bottom: 15px;">
<!-- end header part -->
<!-- Generated by Doxygen 1.8.11 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li class="current"><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
  <div id="navrow3" class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_vars.php"><span>Variables</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;<ul>
<li>addLog()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a0e059fc8f1cb49a4bba283bb05fe2b64">NRE::Tester::TestSuite</a>
</li>
<li>addTest()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a529a5dc5bf235399345229f5d41539f6">NRE::Tester::TestSuite</a>
</li>
<li>getDetails()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a2a0e1e8760903317b3e7bff3d30645db">NRE::Tester::InternalTest</a>
</li>
<li>getTestCase()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a69f9abf82dc49c56a9bb9b65c737358e">NRE::Tester::InternalTest</a>
</li>
<li>getTestName()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a8f2beb5e2fc0123e4881a5d28808438b">NRE::Tester::InternalTest</a>
</li>
<li>hasFailed()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a38fc3c6f7e8a83fd8163f57ad14b3a8d">NRE::Tester::TestSuite</a>
</li>
<li>InternalTest()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a368391c914b73f3dfde897feac112f2e">NRE::Tester::InternalTest</a>
</li>
<li>internalTestBody()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_internal_test.php#a03ce20227a8571daad015075f242107d">NRE::Tester::InternalTest</a>
</li>
<li>runAll()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#aae54422b099fc0bdb5ab24b924e0dff6">NRE::Tester::TestSuite</a>
</li>
<li>runAllTests()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#a467dfe222580814ff230c472b67ed07e">NRE::Tester::TestSuite</a>
</li>
<li>suiteHasFailed()
: <a class="el" href="class_n_r_e_1_1_tester_1_1_test_suite.php#aab8f6475bda093850159149fafcf3dbb">NRE::Tester::TestSuite</a>
</li>
</ul>
</div><!-- contents -->
<!-- HTML footer for doxygen 1.8.8-->
<!-- start footer part -->
</div>
</div>
</div>
</div>
</div>
</div>
</body>
</html>
